---

- name: Search and download Windows updates without installing them
  ansible.windows.win_updates:
    state: downloaded
    reboot: yes

- name: Install all security updates with automatic reboots
  ansible.windows.win_updates:
    category_names:
    - SecurityUpdates
    reboot: yes